project:
  type: website

website:
  title: "Bruno Gondim"
  favicon: cup-hot
  navbar:
    left:
      - href: index.qmd
        text: Página inicial
      - href: Estudos de caso/index.qmd
        text: Estudos de caso
      - href: Aulas/index.qmd
        text: Aulas
      - href: Producao academica/index.qmd
        text: Produção acadêmica
    logo: cup-hot
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/bruno-gondim/
      - icon: github
        href: https://github.com/penasta
      - icon: mailbox
        href: "mailto:brunogtoledo96@gmail.com"

  page-footer: "MIT License 2026, Bruno Gondim."
  open-graph: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true