project:
  type: website

website:
  title: "Bruno Gondim"
  favicon: cup-hot
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Presentations
        menu:
          - href: presentations/nlp/index.qmd
            text: Agrupador de processos de controle concentrado
          - href: presentations/estocasticos/estocasticos.qmd
            text: Processos de Poisson não homogêneos de n tipos
          - href: presentations/churn/relatorio.qmd
            text: Análise de Churn
          - href: presentations/random_forest/apresentacao.qmd
            text: Técnicas de Random Forest em árvores de decisão  
          - href: presentations/xgboost_catboost/trabalho.qmd
            text: XGBoost e Catboost
          - href: presentations/classificacao_salario/trabalho.qmd
            text: Classificação com tidymodels
          - href: presentations/birnbaum/seminario.qmd
            text: Modelo de regressão Birnbaum-Saunders reparametrizado pela média
          - href: presentations/classificação binária de decisões/trabalho_final.qmd
            text: Classificação binária de decisões
          - href: presentations/classificacao_salario_relatorio/trabalho_bruno.qmd
            text: Classificação salarial com Tidymodels
          - href: presentations/npa/lista1.qmd
            text: Geração de NPA's
          - href: presentations/otim_mv/lista2.qmd
            text: Otimização e Máxima Verossimilhança
          - href: presentations/em/lista3.qmd
            text: Algoritmo EM
          - href: presentations/montecarlo/lista4.qmd
            text: Métodos Monte Carlo
          - href: presentations/tcc2/slide.qmd
            text: Similaridade de Processos Judiciários utilizando NLP — Monografia
          - href: https://penasta.shinyapps.io/similaridade_processos/
            text: Similaridade de Processos Judiciários utilizando NLP — Shiny
    logo: cup-hot
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/bruno-gondim/
      - icon: github
        href: https://github.com/penasta
      - icon: mailbox
        href: "mailto:brunogtoledo96@gmail.com"  
  page-footer: "MIT License 2025, Bruno Gondim." 
  open-graph: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true