project:
  type: website

website:
  title: "Bruno Gondim"
  favicon: cup-hot
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Presentations
        menu:
          - href: presentations/nlp/index.qmd
            text: Agrupador de processos de controle concentrado       
          - href: presentations/random_forest/apresentacao.qmd
            text: Técnicas de Random Forest em árvores de decisão  
          - href: presentations/estocasticos/estocasticos.qmd
            text: Processos de Poisson não homogêneos de n tipos
          - href: presentations/xgboost_catboost/trabalho.qmd
            text: XGBoost e Catboost
          - href: presentations/classificacao_salario/trabalho.qmd
            text: Classificação com tidymodels
          - href: presentations/birnbaum/seminario.qmd
            text: Modelo de regressão Birnbaum-Saunders reparametrizado pela média
    logo: cup-hot
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/bruno-gondim/
      - icon: github
        href: https://github.com/penasta
      - icon: mailbox
        href: "mailto:brunogtoledo96@gmail.com"  
  page-footer: "MIT License 2024, Bruno Gondim." 
  open-graph: true

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true