project:
  type: website

website:
  title: "Bruno Gondim"
  favicon: cup-hot
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Case studies/index.qmd
        text: Case studies
      - href: Lectures/index.qmd
        text: Lectures
      - href: Academic production/index.qmd
        text: Academic production
    logo: cup-hot
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/bruno-gondim/
      - icon: github
        href: https://github.com/penasta
      - icon: mailbox
        href: "mailto:brunogtoledo96@gmail.com"

  page-footer: "MIT License 2026, Bruno Gondim."
  open-graph: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true